### ISSUE TITLE
Pull Request #5 pending for a year now

### ISSUE THREAD

**Issue by anomaly256** [CMoH/lg4l#8]
Heyas,   G510 support works just fine.  Can you please merge my pr, #5 ?

**Comment by CMoH** [comment]
Hey. I apologize for not answering for a whole year. I had some health issues, work style changes, and well, lg4l got to be quite low-priority for me.

I'll close this and get back to #5.

**Comment by anomaly256** [comment]
Ouch, sorry to hear that, and understand completely.  Thanks!
